### ISSUE TITLE
utf-8 path names in Linux don't seem to work

### ISSUE THREAD

**Issue by nikoss** [darktrojan/openwith#120]
Hi, 
I am trying to use Open With, with youtube-dl, while setting a directory path with non-english characters. But the UTF-8 part gets corrupted.
(The problem doesn't happen when you just run the terminal with the same command and arguments)

My system
- Mageia Linux
- IceApe 2.40 (SeaMonkey)
- Open With 6.7.2

How to reproduce:
- create a new item in Open With
- set command to: `xterm` or `/usr/bin/xterm`
- set argument to 
`-hold -e youtube-dl --write-all-thumbnails --skip-download -x -o /home/USERNAME/τεμπ/%(title)s-%(id)s.%(ext)s`
- visit any youtube video page and try to use the above item with Open With
- you will probably get something like this:
```
[youtube] KZ8iNDBaGuA: Downloading webpage
[youtube] KZ8iNDBaGuA: Downloading video info webpage
[youtube] KZ8iNDBaGuA: Extracting video information
[youtube] KZ8iNDBaGuA: Downloading MPD manifest
[youtube] KZ8iNDBaGuA: Downloading thumbnail ...
[youtube] KZ8iNDBaGuA: Writing thumbnail to: /home/USERNAME/Äµ¼À/Street Fighting In Athens (1945)-KZ8iNDBaGuA.jpg
```
- the thumbnail got saved in some " Äµ¼À " folder, instead of " τεμπ "

**Comment by darktrojan** [comment]
I'm pretty sure my fix for this is good, but I'm going to play around with it for a while before release just to make sure. This sort of thing tends to lead to more unexpected problems.
