### ISSUE TITLE
WebExtension

### ISSUE THREAD

**Issue by s8321414** [darktrojan/openwith#126]
Any chance to port this extension to WebExtension API? Or it will stop working after Firefox 57.

**Comment by dCosminn** [comment]
Any news on openwith WebExtension?
I really like this one and Nightly 57 will break legacy addons within a week..

**Comment by darktrojan** [comment]
@dCosminn Yes, I have news: there will be one. When it happens is unknown at this stage.

**Comment by KrasnayaPloshchad** [comment]
According to [MAF](https://addons.mozilla.org/en-US/firefox/addon/mozilla-archive-format/) developer such addon will stop working since November 14, 2017.

**Comment by darktrojan** [comment]
Beta 1 is now available. See #132 for more info.

**Comment by dCosminn** [comment]
Once you select a option you can't deselect unless you refresh the page. So if i have a option selected and click "Add browser" to add another program it will overwrite the selected entry.    

It works fine for opening youtube videos in Potplayer using this command: "C:\Program Files\DAUM\PotPlayer\PotPlayerMini64.exe"

It doesn't work on twitch using streamlink. The command I'm trying to use is: "C:\Program Files (x86)\Streamlink\bin\streamlink.exe" -best 
 It worked on the legacy extension, or i had other arguments, i don't remember how i did it.
