### ISSUE TITLE
Not logging to browser console

### ISSUE THREAD

**Issue by Poorchop** [darktrojan/openwith#130]
I'm trying to use a custom command with arguments and it's not working, so I have enabled logging via "Enable log output to Browser Console" in order to troubleshoot but I don't see anything from the add-on in the console. I even tried creating the preference "extensions.sdk.console.logLevel" and setting the value to "all" as recommended elsewhere, but I still don't see anything in the console.

The command in question is calling streamlink.exe with the argument "high,best". It works without any arguments but I'm unable to figure out why it's crashing with the supplied arguments since I can't see any logs. Thanks.

**Comment by darktrojan** [comment]
I was going to ask if you're looking at the web console or the browser console, but you've changed the title now so I'll assume that's not the problem.

I don't know how else I can help. Everything's working as it should be here. Try running Firefox from a command prompt (cmd.exe) and see if output is logged there - it works on Linux, dunno about Windows.

(BTW, that pref you created isn't going to help. Open With isn't an SDK add-on.)

**Comment by Poorchop** [comment]
Launching from a command prompt didn't help. This is a fresh install of Windows 8 and a brand new Firefox profile so I shouldn't have been able to mess up anything yet. I remember having this issue in the past as well.

I'll just test it out in Linux and hopefully I'll be able to troubleshoot from there assuming that logging will work.
