### ISSUE TITLE
WebExtension + MPV, Youtube-DL, Streamlink

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/openwith#133]
These programs seem to cause problems for many people (with the old version and the new one). I don't have experience with any of them, and my focus is on opening browsers for web development. Please use this issue for posting problems or (preferably) solutions.

**Comment by chyiz** [comment]
I have a fix in [my branch](https://github.com/chyiz/openwith/tree/webext-mac-issue-133). It checks the .app extension and chose whether to use `/usr/bin/open`, similar to what the legacy extension was doing. 
It only applies to Mac though. If you think it's good I can send a pull request.

**Comment by darktrojan** [comment]
Looks good to me. It'd never really occurred to me that some things on Mac don't have the .app, which is kinda obvious now that I have thought about it. (No need for a PR, I've already yoinked it. Thanks!)

**Comment by indeedwatson** [comment]
I'm on linux, and due to the way my computer is set up I need to add some env variables before the mpv command. I used to have this working until FF updated to 57 and I installed this WE version and now I can't figure out how to add the ENV variables again.

**Comment by wiiaboo** [comment]
Some way of changing the icons besides using the built-in ones would be nice too.

**Comment by AnonLibre** [comment]
MPV with parameters and custom icon is working as of november 2017.

![MPV example line in Open With WebExtension](https://user-images.githubusercontent.com/15650146/32705916-4599e2a0-c819-11e7-9a6c-4b59617263d0.png)

# Preparations

Follow the steps in the _Open With Options_: _To complete installation_.

Check if `open_with_linux.py` is correctly installed and working.

# Steps

* Go to the _Open With Options_
* Click _Add browser_
  * _Name:_ MPV
  * _Command:_ `/usr/bin/mpv --ytdl-format=bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best --fullscreen %s`
  * _Custom Icons..._ ➜ _Browse..._
  * Select your custom icon in the _Icon:_ window
  * Click the _Add_ button

# Action

Right click on a YouTube link to open the context menu.
It should look something like this:

![Open With context menu example](https://user-images.githubusercontent.com/15650146/32706126-25430822-c81b-11e7-93ca-c113cf03c3d2.png)

I'm using Open With in combination with a RSS reader for YouTube videos and it works great.


Thank you for releasing Open With as a WebExtension!
Your add-on is essential for me.

**Comment by gerroon** [comment]
I use "xterm -e myscript" it works
