### ISSUE TITLE
Is there anything to learn from open external application add on?

### ISSUE THREAD

**Issue by hpvd** [darktrojan/openwith#145]
Just stumbled across this one:
Is there anything to learn from open external application add on?
https://addons.mozilla.org/de/firefox/addon/external-application/?src=search

**Comment by darktrojan** [comment]
Such as?

**Comment by GoodGuyNick** [comment]
dedicated applications buttons in toolbar instead of "Open With" button that contains all applications

**Comment by FearlessPotatoKing** [comment]
I just downloaded it and tested it out, it only lets you pick one application to use as the toolbar button. You can't set multiple buttons. I think this is a new limitation that is imposed on WebExtensions.
