### ISSUE TITLE
Alt+D shortcut is hijacked by OpenWith

### ISSUE THREAD

**Issue by ltGuillaume** [darktrojan/openwith#147]
Whenever OpenWith is updated and the notification bar at the bottom pops up, OpenWith hijacks the Alt+D keyboard shortcut to go to the Donation page. This can only be avoided by restarting Firefox. Alt+D is a default Firefox shortcut to focus the url bar and should not be hijacked by an add-on, especially without any warning. This is very annoying and confusing.

**Comment by darktrojan** [comment]
Hijacked by a Firefox stuff-up, more like. It never used to do that until something changed in Firefox. In any case, there will be no more versions of Open With that have that notification bar.
