### ISSUE TITLE
Passing URL to cmd.exe fails

### ISSUE THREAD

**Issue by vlldk** [darktrojan/openwith#150]
I'm trying to pass an url to cmd.exe but Open With will only output `%s`. I've tried setting the arguments to "%s ", "%s _other arguments_" "%s ""_other arguments_", %s "_other arguments". cmd.exe will only receive `%s` or `%s`

**Comment by darktrojan** [comment]
What version of Open With are you using? Version 6.something will be obsolete very soon.

**Comment by VADemon** [comment]
Firefox Beta on Win7x64 (old pre-WebExtensions version): It has been working for at least 1.5 years now.
Maybe I can help @vlldk

**Comment by vlldk** [comment]
Thank you for your answers! I solved the problem, thank you tho. You can close the problem
