### ISSUE TITLE
open_with_windows.py install

### ISSUE THREAD

**Issue by Judha** [darktrojan/openwith#151]
version 7.0b10 fails on line 73:
file.write('@echo off\r\ncall "%s" "%s" %1 %2\r\n' % (sys.executable, this_file))

maybe this?
file.write('@echo off\r\ncall "%s" "%s" %s %s\r\n' % (sys.executable, this_file, '%1', '%2'))

**Comment by darktrojan** [comment]
Aargh! That worked for me, or so I thought. I can see why it fails though.

**Comment by darktrojan** [comment]
Okay, fixed it. Check for add-on updates and try again.

**Comment by Judha** [comment]
version 7.0b11 confirmed fixed, thx!
