### ISSUE TITLE
Webextension and executing windows command line programs

### ISSUE THREAD

**Issue by virgoparna** [darktrojan/openwith#155]
Webextension version of openwith  does not work with Windows command line programs (like youtube_dl.exe). For them to work in open_with_windows.py subprocess.Popen creationflags must also contain CREATE_NEW_CONSOLE (CREATE_NEW_CONSOLE = 0x00000010). This also works with normal browser without problems.

**Comment by virgoparna** [comment]
This also applies to powershell version. -CreationFlags 0x01000010 works.

**Comment by virgoparna** [comment]
Created pull request for fix

**Comment by monk-time** [comment]
Yeah, I am using 7.0 and can't find any way at all to launch any command line program (including through "cmd /k") like youtube-dl or similar with it. That was the main way I was using this add-on. :(

**Comment by monk-time** [comment]
@virgoparna I can confirm your PR works like a charm on my machine, I was able to reuse my old command for launching youtube-dl without any issues, just like it used to work in the old version. Thank you!

**Comment by darktrojan** [comment]
Things it would've been nice to know *before* release. Sigh.

@virgoparna Thank you for finding and fixing this. You clearly know more about it than I do.

Pushing a new version out now.
