### ISSUE TITLE
WebExt 7.0.1/Firefox 56.0.2 does not work correctly for MS Edge

### ISSUE THREAD

**Issue by TheNec** [darktrojan/openwith#158]
Trying to open a webpage in Edge results in opening %userprofile%\documents

I played around a bit but nothing worked. On the internet I found something that can be used as a workaround:

Change Command

C:\WINDOWS\explorer.exe microsoft-edge:%s

to

C:\Windows\System32\cmd.exe /c start shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge (A brief command shell window appears but for me it's OK)

The helper is installed to C:\Program Files\Mozilla Firefox\browser\extensions and the log does not show anything.

Thanks for your work!

**Comment by darktrojan** [comment]
Edge drives me up the @#^$ing wall.

You can also have `C:\WINDOWS\explorer.exe "microsoft-edge:%s "` (including the stray space). I'm sure I actually fixed that before, but apparently not.
