### ISSUE TITLE
Chrome: "Open With" from link right-click menu doesn't work

### ISSUE THREAD

**Issue by mscha** [darktrojan/openwith#160]
I have Open With 7.0.1 installed in Chrome.
Opening the current page in another browser from the extension icon works just fine.
When right-clicking a link on a webpage, the Open With submenu does appear, with the correct list of browsers, but nothing happens when you choose any of the browsers.  No error appears on the web console.

**Comment by darktrojan** [comment]
Oops, I've clearly changed something there since I last tested it. Fixing it now.

**Comment by mscha** [comment]
Wow, that was fast!
I can confirm that it's now fixed.
