### ISSUE TITLE
Remove Dependency on Python

### ISSUE THREAD

**Issue by stricq** [darktrojan/openwith#167]
Please remove the dependency on Python.

**Comment by soul4soul** [comment]
Similar request was closed as won't fix. See Issue #137. darktrojan did create a powershell script inplace of the python script which works natively with windows.

**Comment by regs01** [comment]
would like not to have python bloatware as well

**Comment by darktrojan** [comment]
You're welcome to install the PowerShell script instead. It's still in this repo, but I am not shipping it.

**Comment by stricq** [comment]
That's fine, I've solved the problem by removing the add-on.
