### ISSUE TITLE
Something went wrong...

### ISSUE THREAD

**Issue by ziceptor** [darktrojan/openwith#168]
Log from console - https://gist.github.com/ziceptor/eef9a3bfd8099bb8a52d1f52a654880e

Win 7 x64
FF 56.0 x64

The script is installed. In folder:
open_with.bat
open_with_chrome.json
open_with_firefox.json
open_with_windows.py

**Comment by darktrojan** [comment]
I meant to reply to this earlier, sorry.

I can get that particular message when if the Open With registry entry doesn't exist. That may not be the only reason, but it's the only one I can think of.

There should be registry entry at `HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\open_with` which points to the open_with_firefox.json file. Perhaps the install step failed to add it.

The corresponding key for Chrome is at `HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\open_with`.

**Comment by ziceptor** [comment]
Yes! This solved the problem! Thank you!

**Comment by ziceptor** [comment]
For me it is:
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts]

[HKEY_CURRENT_USER\Software\Mozilla\NativeMessagingHosts\open_with]
@="G:\\APPDATA\\Mozilla\\Firefox\\Data\\OpenWith\\open_with_firefox.json"
```
For others, the path of the other.

**Comment by ziceptor** [comment]
Section "Mozilla" did not exist. Added manually.

**Comment by darktrojan** [comment]
Yeah I see the problem now, and wouldn't you know, the code causing your install to fail was totally unnecessary anyway.
