### ISSUE TITLE
openwith:auto... Bookmarked URLs Not Working

### ISSUE THREAD

**Issue by misterreed** [darktrojan/openwith#176]
I have the WebExtension installed and working with the Python script, however, none of my bookmarks configured to automagically open in an alternative browser (e.g., openwith:auto.google_chrome:http://cnn.com), are working.

Did this functionality stop working with the converstion to a WebExtension?  If so, is it going to be restored?

Thanks.

**Comment by darktrojan** [comment]
> Did this functionality stop working with the converstion to a WebExtension? If so, is it going to be restored?

Yes it did; no it probably isn't, sorry.

**Comment by misterreed** [comment]
OK.  I'm sorry to hear that.  To me, that is the functionality that made this Add-On standout.
