### ISSUE TITLE
open_with_windows.py not working

### ISSUE THREAD

**Issue by Tback1** [darktrojan/openwith#190]
After an update of firefox from 57 beta 5 to 58 beta1
the openwith is workless.
so I  try to rebuild the .bat and .json file
I've tried the python 2.7.14 and python 3.6.both under Windows 7SP1 64bit
but it just not to work and seems the function install didn't work, and I try to use the pycharm to debug it, it seems **define** the 
`version =7.3 `
than direct goto the bottom line 
`print('Open With native helper, version %s.' % VERSION)`

I checked the reg the HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet is well
and the path of python is well.
I don't know where the environment of system is not fine
but the open_with_windows.py will not to make the bat and json 

```
  "C:\Program Files\Pyhon27\python.exe" C:/openwith/open_with_windows.py install
 Open With native helper, version 7.0.3.
```

```
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> C:\openwith\open_with_windows.py install
  File "<stdin>", line 1
    C:\openwith\open_with_windows.py install
                                           ^
SyntaxError: unexpected character after line continuation character
>>>
```

PS I've  try to use the powershell file to skip the dependency of python.but it not work too.

**Comment by darktrojan** [comment]
>  "C:\Program Files\Pyhon27\python.exe" C:/openwith/open_with_windows.py install

This should work (without the typo). I'm not sure why it doesn't.

If you replace the last line `print('Open With native helper, version %s.' % VERSION)` with `print(sys.argv)` and try again, what happens?

**Comment by Tback1** [comment]
@darktrojan after instead of the print
the  console show me this
`C:\openwith>C:\openwith\open_with_windows.py install
['C:\\openwith\\open_with_windows.py']`

**Comment by Tback1** [comment]
@darktrojan  the powershell give more debug information 
`Windows PowerShell
版权所有 (C) 2009 Microsoft Corporation。保留所有权利。

PS C:\Users\Thresh> c:\openwith\open_with_windows.ps1 install\
PS C:\Users\Thresh> c:\openwith\open_with_windows.ps1 install
Split-Path : 无法将参数绑定到参数“Path”，因为该参数是空值。
所在位置 C:\openwith\open_with_windows.ps1:22 字符: 28
+     $install_path = Split-Path <<<<  $PSCommandPath -Parent
    + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingV
   alidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.SplitPathCommand

Join-Path : 无法将参数绑定到参数“Path”，因为该参数是空值。
所在位置 C:\openwith\open_with_windows.ps1:23 字符: 24
+     $bat_path = (Join-Path <<<<  $install_path -ChildPath 'open_with.bat')
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingVa
   lidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.JoinPathCommand

New-Item : 无法将参数绑定到参数“Path”，因为该参数是空值。
所在位置 C:\openwith\open_with_windows.ps1:24 字符: 23
+     New-Item -Force -Path <<<<  $bat_path -Value (@'
    + CategoryInfo          : InvalidData: (:) [New-Item], ParameterBindingVal
   idationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.NewItemCommand

Get-Item : 无法绑定参数“ErrorAction”。由于枚举值无效，无法将值“Ignore”转换
为类型“System.Management.Automation.ActionPreference”。请指定以下枚举值之一，
然后重试。可能的枚举值为“SilentlyContinue、Stop、Continue、Inquire”。
所在位置 C:\openwith\open_with_windows.ps1:34 字符: 50
+             if (!(Get-Item $registry_location -ErrorAction <<<<  Ignore)) {
    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParameterBindin
   gException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerSh
   ell.Commands.GetItemCommand

Join-Path : 无法将参数绑定到参数“Path”，因为该参数是空值。
所在位置 C:\openwith\open_with_windows.ps1:39 字符: 34
+             $manifest_location = Join-Path <<<<  $install_path -ChildPath ('o
pen_with_' + $browser + '.json')
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingVa
   lidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.JoinPathCommand

Get-Item : 无法绑定参数“ErrorAction”。由于枚举值无效，无法将值“Ignore”转换
为类型“System.Management.Automation.ActionPreference”。请指定以下枚举值之一，
然后重试。可能的枚举值为“SilentlyContinue、Stop、Continue、Inquire”。
所在位置 C:\openwith\open_with_windows.ps1:40 字符: 50
+             if (!(Get-Item $registry_location -ErrorAction <<<<  Ignore)) {
    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParameterBindin
   gException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerSh
   ell.Commands.GetItemCommand

Set-Item : 值不能为空。
参数名: value
所在位置 C:\openwith\open_with_windows.ps1:44 字符: 12
+             Set-Item <<<<  -Path $registry_location -Value $manifest_location
 -Force
    + CategoryInfo          : InvalidArgument: (:) [Set-Item], ArgumentNullExc
   eption
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShel
   l.Commands.SetItemCommand

无法将“ConvertTo-Json”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后重试。
所在位置 C:\openwith\open_with_windows.ps1:51 字符: 87
+             New-Item -Force -Path $manifest_location -Value ($browser_manifes
t | ConvertTo-Json <<<< ) > $null
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-Item : 无法绑定参数“ErrorAction”。由于枚举值无效，无法将值“Ignore”转换
为类型“System.Management.Automation.ActionPreference”。请指定以下枚举值之一，
然后重试。可能的枚举值为“SilentlyContinue、Stop、Continue、Inquire”。
所在位置 C:\openwith\open_with_windows.ps1:34 字符: 50
+             if (!(Get-Item $registry_location -ErrorAction <<<<  Ignore)) {
    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParameterBindin
   gException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerSh
   ell.Commands.GetItemCommand

Join-Path : 无法将参数绑定到参数“Path”，因为该参数是空值。
所在位置 C:\openwith\open_with_windows.ps1:39 字符: 34
+             $manifest_location = Join-Path <<<<  $install_path -ChildPath ('o
pen_with_' + $browser + '.json')
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingVa
   lidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
   icrosoft.PowerShell.Commands.JoinPathCommand

Get-Item : 无法绑定参数“ErrorAction”。由于枚举值无效，无法将值“Ignore”转换
为类型“System.Management.Automation.ActionPreference”。请指定以下枚举值之一，
然后重试。可能的枚举值为“SilentlyContinue、Stop、Continue、Inquire”。
所在位置 C:\openwith\open_with_windows.ps1:40 字符: 50
+             if (!(Get-Item $registry_location -ErrorAction <<<<  Ignore)) {
    + CategoryInfo          : InvalidArgument: (:) [Get-Item], ParameterBindin
   gException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerSh
   ell.Commands.GetItemCommand

Set-Item : 值不能为空。
参数名: value
所在位置 C:\openwith\open_with_windows.ps1:44 字符: 12
+             Set-Item <<<<  -Path $registry_location -Value $manifest_location
 -Force
    + CategoryInfo          : InvalidArgument: (:) [Set-Item], ArgumentNullExc
   eption
    + FullyQualifiedErrorId : System.ArgumentNullException,Microsoft.PowerShel
   l.Commands.SetItemCommand

无法将“ConvertTo-Json”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后重试。
所在位置 C:\openwith\open_with_windows.ps1:51 字符: 87
+             New-Item -Force -Path $manifest_location -Value ($browser_manifes
t | ConvertTo-Json <<<< ) > $null
    + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Thresh>
`

**Comment by darktrojan** [comment]
After reading [this thread](https://stackoverflow.com/questions/29540541/executable-python-script-not-take-sys-argv-in-windows) I suspect it might have the answer you're looking for. You'll have to find the right place in the registry and add the `%*` to get extra arguments sent to Python.

**Comment by Tback1** [comment]
Great，it's work！！！

but it's under this reg
HKEY_CLASSES_ROOT\Applications\python.exe\shell\open\command
set the default item as
"C:\ProgramData\Anaconda3\python.exe" "%1" %*

**Comment by mbooga** [comment]
I'm not sure if it helps, I've made a small launcher for windows that doesn't require Python.
https://github.com/mbooga/owclauncher
