### ISSUE TITLE
Mpv works, but youtube-dl doesn't

### ISSUE THREAD

**Issue by alex3kov** [darktrojan/openwith#194]
Firefox 57.0.2, Arch Linux x64, Open With 7.0.3.  
I have 2 entries in OpenWith:
```
mpv --player-operation-mode=pseudo-gui -- %s
youtube-dl
```
Mpv entry works (plays youtube video), but youtube-dl doesn't download anything. Tried `youtube-dl %s` with the same result. Youtube-dl's config file contains just 1 line `--no-playlist`. OpenWith behaves like this on multiple youtube videos I tried, so it is not related to a specific video. When run from terminal, `youtube-dl` works just fine.  
It worked on pre-firefox-57 version.
I've set `extensions.openwith.log.enabled` to `true`, but there are no OpenWith-related entries in Browser Console when either mpv or youtube-dl entries are clicked. Please let me know what other debugging info I can provide.

**Comment by mbooga** [comment]
I've been debugging open with's output for a while.
It seems that doubles quotes are not properly passed to the launcher.

but if one of your parameters to youtube-dl contains spaces (for example a path), it can help to put it inside double quotes

**Comment by alex3kov** [comment]
I'm not passing any parameters to youtube-dl:  
![2018-01-02-230206_1920x1080_scrot](https://user-images.githubusercontent.com/3616242/34498102-215593c4-f011-11e7-9f78-9d958b705292.png)
Also, it seems that youtube-dl does start when OpenWith entry is clicked, but I don't know where it puts the videos (in pre-57 times it was home directory):
```sh
$ ps -efc |grep youtu
username 25628     1 TS   19 23:02 ?        00:00:01 /usr/bin/python /usr/bin/youtube-dl https://www.youtube.com/watch?v=GZDglvV8Mbw
```

**Comment by alexanderadam** [comment]
@alex3kov I'm not sure about it but you should be able to set the directory with the `-o` / `--output` flag of `youtube-dl`

**Comment by polyzen** [comment]
Please close this.
