### ISSUE TITLE
Stopped working with mpv and scripts

### ISSUE THREAD

**Issue by haadr** [darktrojan/openwith#202]
Firefox ESR 52.5.2 (64-bit) Debian
Open With 6.8.6

Hi,

All I used open with for was mpv. That has stopped working, but I'm not entirely sure when. mpv's log is attached below, but a relevant line seems 

> [ytdl_hook] PermissionError: [Errno 13] Permission denied: '/home/minion/.local/lib/python3.5/site-packages/pkg_resources/__init__.py'. 

However the permissions for that file and the parent directions are good. I even tried giving more permissions than I think is correct:

> -rwxr-xr-x 1 kibitz kibitz 103K sep.   5 17:14 /home/kibitz/.local/lib/python3.5/site-packages/pkg_resources/__init__.py

Note: I can still run the exact same mpv command just fine from the terminal manually. I checked confirmed that the command that works when I run it manually is the same as the one openwith uses by running 

> watch -n 0.2 "ps aux|grep  mpv"

and checking. So mpv does run with openwith, but somehow youtube-dl doesn't run due to permission errors. Openwith also seems to run as my user. I tried creating a simple bash script in my home directory to load mpv for me, but openwith doesn't seem to run that at all.

Any pointers?

Thanks for a great addon!

[mpv.log](https://github.com/darktrojan/openwith/files/1682019/mpv.log)

**Comment by haadr** [comment]
Never mind! Sorry about not investigating more before submitting, I managed to fix it by fixing a broken python environment.

**Comment by polyzen** [comment]
Please close this.
