### ISSUE TITLE
No explanation given for permission change

### ISSUE THREAD

**Issue by Despruk** [darktrojan/openwith#208]
Release notes for 7.1 contain no mention of why the extension suddenly requires to

> Download files and read and modify the browser's download history

This popup seems very ominous
I would expect this makes many users very hesitant about updating

Browser: Firefox 58.0.2
OS: Linux 4.15.3-2-ARCH

**Comment by darktrojan** [comment]
Fair enough. Fixed.

**Comment by bitwombat** [comment]
@darktrojan When I install via addons.mozilla.org (FF 68.0.1) it's still asking for these permissions. These perms also show on the web page for OpenWith on addons.mozilla.org (https://addons.mozilla.org/en-US/firefox/addon/open-with/)

Same with latest beta...
