### ISSUE TITLE
Not working with Thunderbird 60.3.0

### ISSUE THREAD

**Issue by sibberio** [darktrojan/openwith#227]
This fantastic extension is not compatible with the latest version of Thunderbird.
Actually this extension is deactivated.

**Comment by darktrojan** [comment]
It's waiting in the review queue on the add-ons website.

**Comment by sibberio** [comment]
Thank you! I'll way the update

**Comment by sibberio** [comment]
Sorry to reopen this issue but after 16 days the extension still not compatible. It's a long queue or there was some issue?

**Comment by darktrojan** [comment]
Everything should be in order now. Somehow Open With was not copied to the Thunderbird Add-Ons site, which meant it had to go through the full review process, and there aren't many people available to do that.
