### ISSUE TITLE
Doesn't seem to work with IINA on macOS

### ISSUE THREAD

**Issue by JayBrown** [darktrojan/openwith#228]
Has anyone gotten **Open With** to work with IINA on macOS (Mojave 10.14.1)?

See also the topic here: https://github.com/lhc70000/iina/issues/2086

**Comment by krokofant** [comment]
Workaround from the IINA issue:

> So the IINA application is somehow looking if the shell is interactive - and to trick IINA this is not the cause you can use this workaround:
> 1. Install unbuffer from the expect package
>    - `brew install expect`
> 2. Run the iinca-cli via `unbuffer`
>    - Add this as the OpenWith command `/usr/local/bin/unbuffer -p /Applications/IINA.app/Contents/MacOS/iina-cli`

**Comment by JayBrown** [comment]
Confirmed working with the new IINA release. Add the following in the Firefox **Open With** extension: `"/usr/local/bin/iina --no-stdin"`

(In this case the `iina-cli` is symlinked to `iina` in `/usr/local/bin/`. If you haven't done so, substitute `/usr/local/bin/iina` for the path to `iina-cli` in the main IINA bundle at `./Contents/MacOS/iina-cli`.
