### ISSUE TITLE
Waterfox Current 2020.01 - Not Working

### ISSUE THREAD

**Issue by lucknaumann** [darktrojan/openwith#256]
- **OS** = Windows 10 v1809
- **Browser** = Waterfox Current 2020.01 (was 2019.10, then 2019.12) [**beta** -- so I understand if this is unsupported]
- **Add-on version** = latest -- 7.2.1 (also tried 7.1 and 7.0.3)
- **Works in** = FF 72.0.1 _and_  WF Classic 2020.01 (v7.0.3)
- **Brief History** = Haven't used WF Current very long (only installed it as of version 2019.10). 
I believe it's based on FF 68. 
Just tried add-on within the past few weeks and Test Installation doesn't work. 
Have tried a similar add-on [from here](https://add0n.com/open-in.html) and it worked (uses a different method, I believe). 
- **Other Info** = there is no way to turn on logging as per instructions [here](https://github.com/darktrojan/openwith/blob/master/CONTRIBUTING.md#what-to-put-in-your-bug-report).
- **Have created an issue** in the WF repository [here](https://github.com/MrAlex94/Waterfox/issues/1330#issue-542649703). I decided to post one here just in case.

Edit: Error Message from add-on:

- Something went wrong. There might be more information in the Browser Console.

Browser Console:

- No such native application open_with NativeMessaging.jsm:112

 - startupPromise resource://gre/modules/NativeMessaging.jsm:112

**Comment by grahamperrin** [comment]
#250 includes a patch for Brave. 

Optimistically: a single PR at https://github.com/darktrojan/openwith/pulls might add support for both Waterfox Current _and_ Brave.

**Comment by jericocoa** [comment]
Windows 10 (1909)
Waterfox Current registry key: HKCU\Software\Waterfox

need to update registry_locations, browser_manifest
see patch
[WFCurrent_open_with_windows.py.patch.txt](https://github.com/darktrojan/openwith/files/4743786/WFCurrent_open_with_windows.py.patch.txt)

**Comment by lucknaumann** [comment]
[**@jericocoa**](https://github.com/jericocoa) commented on [Jun 7, 2020, 9:06 PM MST](https://github.com/darktrojan/openwith/issues/256#issuecomment-640352405 "2020-06-08T04:06:51Z - Replied by Github Reply Comments"):
> Windows 10 (1909)  
> Waterfox Current registry key: HKCU\\Software\\Waterfox
> 
> need to update registry\_locations, browser\_manifest  
> see patch  
> [WFCurrent\_open\_with\_windows.py.patch.txt](https://github.com/darktrojan/openwith/files/4743786/WFCurrent_open_with_windows.py.patch.txt)

Thanks for this! You Rock! 😄 
WF 2020.06
