### ISSUE TITLE
Add an option to use a keyboard shortcut

### ISSUE THREAD

**Issue by felagund** [darktrojan/openwith#28]
I am not usre if I am not missing anything, but I would like to open a page in another browser using a shortcut. Would that be possible?

**Comment by robin007bond** [comment]
Same! This would be a great feature.

**Comment by Shudouken** [comment]
I'd like to see this too, right click + key is so much more comfortable

**Comment by darktrojan** [comment]
I'm going to do this. It seems like a good idea, although there's a shortage of unused key combinations in Firefox.

**Comment by darktrojan** [comment]
I'm calling this finished! Woohoo!

(Checkout `unreleased` branch if you want to test it.)
