### ISSUE TITLE
Right clicking on link opens tab's address

### ISSUE THREAD

**Issue by dubhater** [darktrojan/openwith#297]
Hi! I just got the 7.2.4 update and now I can't open any links by right clicking on one and selecting the application I configured in openwith. Instead of sending the link to the application, openwith sends the tab's address.

Could it be because of https://github.com/darktrojan/openwith/pull/272 ? It's the only change since 7.2.3 which looks related to addresses.

I'm using Firefox 84.0.2 in Linux.

**Comment by glesialo** [comment]
I can confirm the bug in firefox 85.0 (Linux). Bug is very recent (working all right one or two days ago) and updating 'open_with_linux.py' to 7.2.3 doesn't help :-(

**Comment by burnuser** [comment]
Same Problem with Open With 7.2.4 in Thunderbird 78.7 on Windows 10
Any selected Link tries to open the Message (Tab) itself instead of the link in the selected Webbrowser (=> error!)
