### ISSUE TITLE
Not working with thunderbird release 78.7.0 64bit?

### ISSUE THREAD

**Issue by greenflute** [darktrojan/openwith#298]
Mac OSX Mojave 10.14.6 
Thunderbird 78.7.0

after upgrade to 78.7.0, again it won't work any more, deinstall and reinstall the plugin in thunderbird is not helping.

download the latest open_with_mac.py (Open With native helper, version 7.2.4), 
tried with "python3 open_with_mac.py install", no errors reported. but the plugin still not working.

any chance that some kind of log information written by the plugin so we can look into it? great thanks in advance :)

**Comment by LinuxOpa** [comment]
7.24 not working in TB 78.7.0, doesn't open the links in Chrome or Firefox; downgrade to 7.23 and all ok again.

**Comment by greenflute** [comment]
great, works like a charm , respect :)

**Comment by LinuxOpa** [comment]
but this is only an interim solution until the bug is fixed in 7.24

**Comment by LinuxOpa** [comment]
7.2.5 fixed the bug from 7.2.4, thanks for that.
