### ISSUE TITLE
open with doesn't work anymore in Thunderbird

### ISSUE THREAD

**Issue by DoctorSubtilis** [darktrojan/openwith#302]
I mean, in the last release of ThunderBird.  
Even following your instructions (open_with_linux.py).

**Comment by DoctorSubtilis** [comment]
always the same message:  

    Something went wrong. There might be more information in the Browser Console.  

Why it's now so complicated?

**Comment by jezdinsky** [comment]
I encountered this problem, too. It was caused by antivirus/firewall Comodo. The script was rated "unrecognized" and was blocked and not allowed to create the necessary files. If you use Comodo, you have to go to Settings / File Rating / File list and change the file open_with_windows.py rating to Trusted, then run it again. The installation is successful when one .bat and several .json files are created in the directory where open_with_windows.py resides.

**Comment by DoctorSubtilis** [comment]
I see. I tried disabling the firewall (not Comodo), but unsuccessfully.

**Comment by artk47** [comment]
I experience the very look-like issue on Chrome now:
![image](https://user-images.githubusercontent.com/8707649/113411256-fb59cb00-93bd-11eb-8738-7d23f90907db.png)
Tried to reinstall multiple times with turning off firewalls and any blockers (i use only ObjectiveSee tools which is very unintrusive), but still see the same error.
It's strange it is pointing to the 1st line of script..

**Comment by guest73** [comment]
And I get this error 
`Unchecked runtime.lastError: Specified native messaging host not found.`
It is all because chromium is distributed as SNAP package now.

**Comment by guest73** [comment]
It is working though for my SlimJet installation and Google chrome because they are not stupid SNAPs.

**Comment by DoctorSubtilis** [comment]
But are you speaking about a Thunderbird add-on or about an add-on of some browser?

**Comment by artk47** [comment]
> But are you speaking about a Thunderbird add-on or about an add-on of some browser?

I talk about Chrome specifically, any advices?

**Comment by DoctorSubtilis** [comment]
> > But are you speaking about a Thunderbird add-on or about an add-on of some browser?
> 
> I talk about Chrome specifically, any advices?

I just like to know how get this add-onn working in Thunderbird :)

**Comment by pdftk** [comment]
I did successfully reinstall it. The already updated old Installation of the script (before Thunderbird 78) would not let me add new browsers.
With that said, it was a tad fiddling. I think, moving around of the open_with_linux.py file does not work(weird). Just download it to the place you want to store it. And then do the following steps.

**Comment by DoctorSubtilis** [comment]
No: I get always the same error: «Something went wrong. There might be more information in the Browser Console.»
And in the konsole: moz-extension://a7758887-2c6e-4366-9ef6-23d155628682/options.html
What a nightmare!
Couldn't you do as all other add-ons, less complicated?
Thanks

**Comment by DoctorSubtilis** [comment]
> I did successfully reinstall it. The already updated old Installation of the script (before Thunderbird 78) would not let me add new browsers.
> With that said, it was a tad fiddling. I think, moving around of the open_with_linux.py file does not work(weird). Just download it to the place you want to store it. And then **do the following steps**.

what **steps** are you speaking about?
Here there is nothing to do: in TB this extension doesn't work at all.

**Comment by pdftk** [comment]
There used to be a python script associated with the installation of this addon in Thunderbird.

**Comment by darktrojan** [comment]
Open With absolutely does work with Thunderbird. I just used it to open this page.

The current version is 7.2.5. Make sure you have that. [Get it from here.](https://addons.thunderbird.net/en-US/thunderbird/addon/open-with/) Then go to the Open With preferences page and follow the installation instructions.

**Comment by DoctorSubtilis** [comment]
I have done all you said, but nothing to do: always the same message:  

    Something went wrong. There might be more information in the Browser Console.

and Open With doesn't work! I have KDE Neon.
What could be the cause?
