### ISSUE TITLE
Excessive memory usage?  19.5 MB per Browser

### ISSUE THREAD

**Issue by craiglondon** [darktrojan/openwith#31]
See attached
![openwith-19mb](https://cloud.githubusercontent.com/assets/3833140/7066789/febcc8e6-de93-11e4-9cc0-ba49c280f402.JPG)

**Comment by darktrojan** [comment]
That's very likely to be a bug in Firefox. I've seen it now too. I'll investigate.

**Comment by darktrojan** [comment]
Reported https://bugzil.la/1152766

**Comment by darktrojan** [comment]
This has been fixed in Firefox 38.
