### ISSUE TITLE
The failing of a process is insanely obtuse.

### ISSUE THREAD

**Issue by SuperSonicHub1** [darktrojan/openwith#312]
There are times when you'll run a command and nothing will happen. This would be fine if the extension had a log of some kind, but it doesn't, so you're unfortunately left scratching your head why something didn't work. Having the Python scripts write a log to a text file in a temporary file with the `tempfile` and `logging` modules would make debugging a lot easier. The Open With extension's icon should also flash an error if the process you're running returns a non-zero exit status.

**Comment by smitgd** [comment]
This must be why I see nothing at all in console when I tried to do this:
https://superuser.com/questions/830039/firefox-how-to-open-a-link-to-any-text-based-file-in-vim
when trying to open text files into gvim via firefox links.
