### ISSUE TITLE
Cannot install open_with_windows.py

### ISSUE THREAD

**Issue by Andy-the-Bee** [darktrojan/openwith#328]
HI
I'm runnning Firefox 98.02 on WIndows 10  and am having problems getting this extension to function. After running "open_with_windows.py install" via an elevated command prompt on the downloaded python file and testing via the button on the "Open With Options" page I get the error message:

"Something went wrong. There might be more information in the Browser Console"

I have Python 3.10 installed via the Microsofr Store. I get the same error on the Chrome browser where I have also installed the chrome version of this extension. Seems to me that the python file is not being installed correctly for some reason.
Can anybody help?
Thanks ...

![$__OpenWith Error](https://user-images.githubusercontent.com/29046839/161060643-6089b536-3cc0-4f0e-ba4c-ddec78ef6710.png)

**Comment by tylvn** [comment]
`open_with_windows.py` will be opened by VS Code when I run `open_with_windows.py install` in cmd. #321 has appeared before.

**Comment by Andy-the-Bee** [comment]
Thanks, but fat lot of use that is to me. I'm closing this thread, have moved on to a different extension anyway.

**Comment by sylph520** [comment]
> Thanks, but fat lot of use that is to me. I'm closing this thread, have moved on to a different extension anyway.

Same problems here, may I ask what extension have your moved to? thanks!

**Comment by Andy-the-Bee** [comment]
@sylph520 
"Open in Chrome Browser" by Andy Portmen:

https://addons.mozilla.org/en-GB/firefox/addon/open-in-chrome-browser/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

He has also written other extensions for different browsers, including Opera.
Hope that's of some use for you.

**Comment by sylph520** [comment]
@Andy-the-Bee  thanks, I'll check it out!
