### ISSUE TITLE
Open .cmd files and such?

### ISSUE THREAD

**Issue by Chaquator** [darktrojan/openwith#33]
I'm trying to be able to open torrent links from [HorribleSubs](http://horriblesubs.info/) through peerflix, but to open peerflix would be running node.js and running the app.js for peerflix or opening peerflix.cmd, wherever it's located.

**Comment by darktrojan** [comment]
.cmd is just a batch file isn't it? Open With should be able to make those run.

… or am I missing something?

**Comment by Chaquator** [comment]
Open With only runs .exe and .com, and I believe .cmd files aren't backwards compatible with .bat

**Comment by darktrojan** [comment]
Okay, I see the problem. I've added "All Files" as an option to the file picker. That should just work.

**Comment by Chaquator** [comment]
Awesome. How can I manually update the plugin? Hasn't appeared on the thing as of yet, even when reinstalling.
I'll wait till later to try again.

**Comment by darktrojan** [comment]
I haven't released anything with those changes yet, but that should be happening in the next few days.
