### ISSUE TITLE
Open With 5.8 causes problems with Seamonkey 2.33.1

### ISSUE THREAD

**Issue by duey** [darktrojan/openwith#36]
Hello,

I happened to update SeaMonkey and Open With around the same time.  And, now I'm experiencing some weird issues.

Previous versions:  SeaMonkey 2.31, Open With 5.7.2  (it seems that 5.8 isn't compatible with 2.31)

I'm using Seamonkey Portable.  But, I tested with a fresh install of SeaMonkey 2.33.1 (the original, not portable one, using Windows 10 in VirtualBox in case you're wondering), and I got the same issue.

So, anyways, when I use 5.8, various things happen, such as a "phantom tab" is opened in all windows (doesn't show up unless I drop down the list of tabs in the tab bar).  Session restore doesn't seem to work.  The Add-ons Manager doesn't open when selected from the Tools menu (however, I can open it manually by typing "about:addons" in the URL bar).  I can't open the Open With Options.  

I realize this isn't much to go on.  How can I help you investigate this?

Duey

**Comment by duey** [comment]
Ooops, forgot to add:

User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1
Build identifier: 20150321194901

**Comment by darktrojan** [comment]
Thanks for filing this. I've meant to ask for more info after a few review comments, but haven't had time.

I couldn't reproduce any problems at all yesterday but now I can … this is odd. Will investigate.

**Comment by darktrojan** [comment]
Okay, I've put a fixed version up on AMO, just awaiting a reviewer. Alternatively you could get it from https://addons.mozilla.org/en-US/firefox/addon/open-with/versions/5.8.1 

My apologies, I've no idea how that slipped through my testing (or why the change I made caused a problem in the first place).

**Comment by duey** [comment]
That you for the quick response!  The update was available in Mozilla Addons, so, I just did the upgrade there.  Working good now.  :)
