### ISSUE TITLE
Can't call program with quote-wrapped parameters

### ISSUE THREAD

**Issue by Atario** [darktrojan/openwith#41]
I set my arguments to

`-profile="Normal" -url="%s"`

but the called program receives

`-profile=Normal -url=%s http://example.com/foo?bar=1&baz=2`

Oddly, I get the exact same result if I remove the quotes.

**Comment by darktrojan** [comment]
It's not the quotes that cause a problem, it's the `-url=`. Open With isn't seeing the `%s` because it's expecting `%s` to be by itself. I'll fix that and hopefully not break something else in the process.
