### ISSUE TITLE
URL in plain text

### ISSUE THREAD

**Issue by Najoj** [darktrojan/openwith#42]
Marking a URL in plain text, Firefox gives the right-click options to open the link, but Open with (this add-on) is nowhere to be found.

For example this link:

    www.github.com

Image:
![openwith](https://cloud.githubusercontent.com/assets/7316177/8635220/07049fae-281a-11e5-9a56-86aad4ba2966.png)

It would be nice to have Open with in this menu.

**Comment by darktrojan** [comment]
Thanks for the suggestion.
