### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by wikiped** [darktrojan/openwith#46]
Edge - the new browser name in Windows 10 - can't be launched just by calling exe file.
It has to be called like this from command line:
`explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge` [source](http://answers.microsoft.com/en-us/insider/forum/insider_internet-insider_spartan/how-to-start-microsoft-edge-from-command-line/25d0ba93-4e8b-41cb-adde-461d8fb58ec1?auth=1)

Adding this to `openwith` as arguments to `c:\windows\explorer.exe` doesn't work.

It appears that Edge needs to have some sort of exception to allow either a custom command line (without the need to point to exe file through explorer) or a completely predefined menu item.

What  do you think?

**Comment by darktrojan** [comment]
Oh hell, they have to make life difficult, don't they? That said, I don't see any reason why it shouldn't work using arguments. Can you set `extensions.openwith.log.enabled` to true and try again? I'd like to see if those args are handled correctly.

**Comment by wikiped** [comment]
Thanks for prompt reply.
I have enabled log, but can't find the log file (`extension.log` in profile folder does not show anything).

I also tried manually editing `extensions.openwith.manual.DbpTQsF1` to be `"C:\Windows\explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"`, but still nothing happens.

**Comment by darktrojan** [comment]
I should've said, the log goes to the browser console (in the web developer tools or Ctrl+Shift+J).

**Comment by wikiped** [comment]
This is what is logged in the console: 
`File not found          openwith.jsm:453:0`
When the input in `extensions.openwith.manual.DbpTQsF1` is: `"C:\Windows\explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"`

**Comment by darktrojan** [comment]
Try it with quotes around the .exe:
`"C:\Windows\explorer.exe" shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge`

I haven't got Windows 10 yet so I can't test this, unfortunately.

**Comment by wikiped** [comment]
I have tried quotes around `"C:\Windows\explorer.exe"` - it opens Explorer window (as in "File Explorer"), with this lines in log:

	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowsRegKey.readStringValue]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://openwith/openwith.jsm :: OpenWithCore.loadList :: line 57"  data: no] openwith.jsm:85:0
	OpenWith: reloading lists openwith.jsm:194:3
	Mozilla Firefox (hidden):
		Command: C:\Program Files (x86)\Mozilla Firefox\firefox.exe
		Params: 
		Icon URL: moz-icon:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/firefox.exe?size=16 openwith.jsm:196:1
	Microsoft Edge:
		Command: C:\Windows\explorer.exe
		Params: shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge
		Icon URL: moz-icon:file:///C:/Windows/explorer.exe?size=16 openwith.jsm:196:1
	OpenWith: opening
		Command: C:\Windows\explorer.exe
		Params: shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge about:config openwith.jsm:444:1
	
Also tried quotes around each part `"C:\Windows\explorer.exe" "shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"`,
as well as:
`cmd /c "C:\Windows\explorer.exe shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"`
 with similar result:
	
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowsRegKey.readStringValue]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://openwith/openwith.jsm :: OpenWithCore.loadList :: line 57"  data: no] openwith.jsm:85:0
	OpenWith: reloading lists openwith.jsm:194:3
	Mozilla Firefox (hidden):
		Command: C:\Program Files (x86)\Mozilla Firefox\firefox.exe
		Params: 
		Icon URL: moz-icon:file:///C:/Program%20Files%20(x86)/Mozilla%20Firefox/firefox.exe?size=16 openwith.jsm:196:1
	Microsoft Edge:
		Command: C:\Windows\explorer.exe
		Params: "shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"
		Icon URL: moz-icon:file:///C:/Windows/explorer.exe?size=16 openwith.jsm:196:1
	OpenWith: opening
		Command: C:\Windows\explorer.exe
		Params: shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge about:config openwith.jsm:444:1

I did a bit of searching and it turns out to launch Edge with an url it can be called like this:
`start microsoft-edge:url`. Which works fine if entered in command line, but it does not work as intended in FF - it opens Explorer window (as in "File Explorer") - which is the last successful call I believe, with this lines in log:
	
	[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIWindowsRegKey.readStringValue]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://openwith/openwith.jsm :: OpenWithCore.loadList :: line 57"  data: no] openwith.jsm:85:0
	NS_ERROR_FILE_UNRECOGNIZED_PATH: Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsILocalFile.initWithPath] openwith.jsm:152:0
	OpenWith: opening
		Command: C:\Windows\explorer.exe
		Params: shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge about:config openwith.jsm:444:1
		
		
And I also tried may combinations of quotes with `start microsoft-edge:url`, but all giving the same result...:

	"start microsoft-edge"
	"start microsoft-edge:%s"
	"start microsoft-edge:"%s""
	"start "microsoft-edge:"%s"""
	start "microsoft-edge:"%s
	start "microsoft-edge:%s"
	start "microsoft-edge:"%s""
	cmd /C start microsoft-edge:"%s"
	cmd /C "start microsoft-edge:"%s""
	cmd /S "start microsoft-edge:%s"
	cmd /S /K "start microsoft-edge:%s"
	
They indeed do make it quite 'Edgy'...

**Comment by mherz73** [comment]
I am trying to use the follow for the "Command"
C:\Windows\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe
However no luck so far with finding the right "Arguments"

Some food for thought.

**Comment by darktrojan** [comment]
I finally have Windows 10. This command works for me:

`"C:\Windows\explorer.exe" microsoft-edge:%s`

**Comment by darktrojan** [comment]
To set the icon you can use this pref:

`extensions.openwith.manual.xxxxxxxx.icon` `moz-icon:file:///c:/windows/SystemApps/Microsoft.MicrosoftEdge_8wekyb3d8bbwe/MicrosoftEdge.exe?size=16`

**Comment by wikiped** [comment]
Hmm, How could I miss this combination :-)

Works for me too, thanks.

**Comment by darktrojan** [comment]
I'm leaving this open to make it easier to find.
