### ISSUE TITLE
Edge buttons open Windows Explorer for some people

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/openwith#51]
Bah!

I don't know why this is, so if anyone has some insight, please say so.

**Comment by darktrojan** [comment]
Okay, I've learned a thing or two and I'm going to replace the current command:
`C:\Windows\explorer.exe microsoft-edge:%s`

With:
`C:\Windows\system32\cmd.exe /c start microsoft-edge:%s`

And also to escape `&` in the URL as `^&`. This seems to work, but I hate it. And Windows in general.

**Comment by vyv03354** [comment]
If the URL contains an ampersand (`&`), Explorer will not parse the command-line correctly without quoting the parameter.

nsIProcess will automatically quote the parameter when it contains a whitespace, but it will not take care of ampersands.

My workaround is adding a trailing space character. That is:
``` C:\Windows\explorer.exe "microsoft-edge:%s "```
Fortunately, Edge seems to ignore the trailing whitespace.

**Comment by darktrojan** [comment]
Yes, that does appear to work. I think it's an easier fix that what I was going to do before, even if it is an ugly hack. (Let's face it, if you're using Windows, you're used to ugly hacks.)

**Comment by darktrojan** [comment]
Open With 6.0.1 with this change has been released and approved. Thanks for your help, @vyv03354.
