### ISSUE TITLE
Unmaintained translations at risk of removal

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/openwith#56]
I've decided that it's not worth maintaining the translations which haven't been updated for a long time. They are likely to be removed.

At risk: ~~Arabic~~, ~~Brazilian Portuguese~~, Bulgarian, Catalan, ~~Chinese (Simplified)~~, ~~Czech~~, Finnish, ~~French~~, ~~German~~, Hungarian, Icelandic, ~~Italian~~, ~~Polish~~, ~~Portuguese~~, ~~Russian~~, Serbian, ~~Spanish (Spain)~~, ~~Ukrainian~~, ~~Vietnamese~~. Each of these is missing a large number of strings.

I don't want to annoy a lot of users by having their software revert to English, but I think they would rather have it all in English than half (or more) in English, half in another language.

If you can help, send a pull request (to branch `unreleased`), or visit https://zoo2translate.herokuapp.com/darktrojan/openwith, which makes the process easier.

**Comment by VADemon** [comment]
I claim German and Russian. In fact, I've tried to update Russian but I barely knew where exactly a string is used // lack of description.

**Comment by darktrojan** [comment]
@VADemon That was quick! I apologise for the lack of comments in my string files, I will be making an effort to improve them. Do what you can and ask any questions you have, and I will try to answer them quickly.

**Comment by xXJOKRXx** [comment]
I've just finished translating Open With to the Arabic language.
Please notice that some words "Like Control, Alt, Shift" has no actual meaning in arabic so just leave it the same.

**Comment by rcmero** [comment]
Claiming European Portuguese translation. This extension is very helpful to me (especially on my laptop, as I also have Chrome, IE and Edge installed), so I am happy to help in any way I can.

**Comment by ram-you** [comment]
Ok, I can for French.

**Comment by Krzysiu** [comment]
I'm Polish app translator with good knowledge of language and IT terminology and with long experience in translating applications. Please note that my spoken English is bad.

**Comment by darktrojan** [comment]
Many thanks to all of you who have helped out so far! I hope to release a version containing your work in the next few days, so you and others can use Open With in your own language.

**Comment by gojira86** [comment]
I might be able to help with Finnish translation? I don't have experience with app translations, but I am a language student with previous experience on other kinds of translation.

**Comment by enricoweb** [comment]
If you do not hurry, I can translate into Italian

**Comment by private-lock** [comment]
German is done.

@VADemon ... sorry, I didn't check, that you'd already claimed it ...

**Comment by SmashDde** [comment]
Is Zoo supposed to provide an inline editor for the needed translations? If so, I'm not getting any, maybe because of the German translation being marked as done? Anyhow, thanks for the extension, pretty useful both on my PC and Mac. :+1:

**Comment by muflone** [comment]
I could take care of the Italian translation

**Comment by darktrojan** [comment]
@SmashDde Yes, someone's already claimed German, so you won't be able to edit it. Thank you anyway!

**Comment by VADemon** [comment]
Sorry, I've been busy the entire week. Can I get the permission to edit Russian translation? Just to fix 2 or 3 misspellings.

**Comment by csolisr** [comment]
I'd claim Spanish (America) if it were on the list. I might check Spanish (Spain) to use it as a base though.

**Comment by darktrojan** [comment]
@VADemon The best way to do that might be to make comments on #64. You should be able to comment on individual lines.

@csolisr I'm not sure how Mozilla code handles Spanish for Latin America. I'll investigate for you.

**Comment by darktrojan** [comment]
@csolisr Okay, I'd been thinking of es-LA, not es-AM. No wonder I couldn't make things work. I've added es-AM to Zoo, so it's available now.

**Comment by Krzysiu** [comment]
Mister @darktrojan - do you also accept translations for language, which never is the only language? It's the local language in Poland, so everybody knows Polish as well. Translated application is e.g. MediaWiki. But that would be more like interesting/cool stuff than something really needed for the reasons I said on the top. What I mean is https://en.wikipedia.org/wiki/Silesian_language

**Comment by VADemon** [comment]
@darktrojan commented my suggestions on #64.

**Comment by webgobe** [comment]
Claiming Hungarian.

**Comment by sveinki** [comment]
I've fully translated Icelandic on Babelzilla, been testing for a while now.
Please re-enable Icelandic.
