### ISSUE TITLE
[Request] Support menu accelerators

### ISSUE THREAD

**Issue by spxxxk** [darktrojan/openwith#57]
I'm talking about shortcuts in menus (such as right-click menu).
Default accelerators would do, custom ones would more than just do.

Right click on a link, press 'm' -> opens links in mpv !

No idea if firefox can let addons do that.

**Comment by darktrojan** [comment]
I was thinking about this just the other day. I don't know why it hasn't occurred to me in all the years since I first wrote Open With, but it's a good idea.
