### ISSUE TITLE
Bookmarkable links to open other browsers

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/openwith#82]
I've had a request to be able to save a bookmark that opens in another browser. I think this is a good idea, so intend to implement it.

Currently the plan is to create the `openwith:` protocol which opens the other browser when an URL is requested. URLs would be of the form `openwith:browser.identifier:https://foo.com/`, where `browser.identifier` is the identifier used to set prefs, e.g. `auto.chromium` or `manual.2wLQck1O`. I've implemented the protocol, now I'm just looking for way(s) to make good UI.

**Comment by darktrojan** [comment]
Work in progress is on branch `protocol`.

**Comment by darktrojan** [comment]
The `openwith` URL scheme landed in Open With 6.3, but there is no UI for it.

**Comment by MurzNN** [comment]
Thanks, this is good solution, but I try Open With 6.3 version on Firefox 41 and this is not work for me.
I create html with code `<a href="openwidth:manual.2f0GNL6J:ftp://myserver.com/">link</a>` and on click it opens link in Firefox with error "The address wasn't understood" instead of external app. Maybe we need manually register  `openwith:` protocol in Firefox?
identifier I have found in about:config string.

**Comment by MurzNN** [comment]
Sorry, `openwidth` is not `openwith` :)

**Comment by MurzNN** [comment]
On clear profile it not works too. When I bookmark link like `openwith:manual.2f0GNL6J:http://google.com/` or like `openwith:auto.chromium:http://google.com/` - nothing happens too.
 Maybe we must change some Firefox security settings for open those lins?

**Comment by MurzNN** [comment]
I have create the GreaceMonkey userscript that automate opening links via specific openwith options, here is the code and examples: https://github.com/Qseo/OpenWithLink

**Comment by AndydeCleyre** [comment]
Please document this.

How can we find the `browser.identifier`?

How can we associate `openwith:` URIs with the extension? Firefox asks to associate it with an external app.

**Comment by darktrojan** [comment]
@AndydeCleyre You can't. It doesn't work any more.
