### ISSUE TITLE
Quoted arguments revisited

### ISSUE THREAD

**Issue by Atario** [darktrojan/openwith#83]
I just again tried the issue I reported before in #41, and it's different now, but it still doesn't work.  Now when I try

    -profile="Normal" -url="%s"

I get

    -profile=Normal -url=http://example.com/foo?bar=1&baz=2

Still no quotes, in other words.  And yes, it does make a difference.  The specific case I'm trying is with [µTorrent Adder](https://sites.google.com/site/ultimasites/utorrent-adder), if that helps.  It gives the error "The profile, 'True', does not exist".  Not sure how it even received "true" instead of "Normal".

In trying to figure this out, I also tried using cmd.exe as a program and

    /k echo -profile="Normal" -url="%s"

as a test case.  The "&" in the url seems to get treated as a command delimiter or something by the system, so it tries to execute what's after it as a second command instead.  Or something.

**Comment by darktrojan** [comment]
Okay, I'm sick of dealing with quotes, so I've just pushed a change that will force them to stick around if you escape them e.g. `--url=\"%s\"`.

Other things you could try in the meantime:
* use single quotes
* `-url="%s "` - the extra space seems to make cmd.exe deal with things differently. Go figure.

**Comment by VADemon** [comment]
Try ^ as the escape character on Windows.
Similar: #52

**Comment by Atario** [comment]
The \" works!

Thanks, darktrojan!
