### ISSUE TITLE
[Feature request] Set per-link types for always use specific apps via Open With by default

### ISSUE THREAD

**Issue by MurzNN** [darktrojan/openwith#86]
I have use Open With extension with corporate system and always use one Open With option for some link types.
For example, our corporate system works normally only in Chrome, so I always open links to it in Chrome via Open With extension and manually select Chrome.
When I open links to local files (file://), I use "Open With Dolphin" (I use Linux system with KDE) to open full file explorer, when use FTP link - open FTP client instead of Firefox, when SFTP  - open Krusader sftp client, etc.

So will be good to have ability for mark some links in HTML code to always use direct Open With item on click, without use menu. For example, we can use CSS class for links, like:
```
<a href='https://corp.mycompany.com' class="open-with-chrome">Corporate system</a>
<a href='file:///home/user/folder' class="open-with-dolphin">Open folder</a>
<a href='sftp://myserver.com/myfolder' class="open-with-krusader">server SFTP</a>
```
If we have no access to edit HTML source of page on server side, we can add this classes to any page via custom Greasemonkey script.

So with this feature we can tune-up auto opening needed links with specific apps without many clicks.

What do you think about this idea?

**Comment by darktrojan** [comment]
If you're willing to use Greasemonkey you should be able to do something like this with #82. The parts you'd need are in the latest version.

**Comment by VADemon** [comment]
I do not really understand you. Firefox already allows you to select applications to open certain protocols with. If you want change the default behavior - go to Firefox' options. (Works FTP/SFTP examples, not sure if you can set file:// to be opened with an external app)
The only reason to use OpenWith here is when you want to ocasionally override the default behavior (say, use YahooMail instead of GMail on a specific mailto: link, or http(s):// for specific websites)

**Comment by MurzNN** [comment]
If describe simply, I need to always open http://onesite.com link via Firefox, http://secondsite.com always via Chrome, http://thirdsite.com always via IE, etc.
Now I must don't forget to select this manually, I want to automate this thing.

**Comment by MurzNN** [comment]
Yes, #82 is same feature request, so will wait for new release to testing.

**Comment by darktrojan** [comment]
@MurzNN you can use `openwith` URLs already, if you're up-to-date.

**Comment by MurzNN** [comment]
Duplicate of #82
