### ISSUE TITLE
toolbar icons abnormal

### ISSUE THREAD

**Issue by yym2** [darktrojan/openwith#89]
<img width="450" alt="screen shot 2015-12-04 at 20 03 31" src="https://cloud.githubusercontent.com/assets/4157030/11583769/58a53ccc-9ac2-11e5-805b-9b5abd23b5d4.png">
Toolbar icons are much bigger than the others.

OSX 10.11 FireFox 42.0 Open With 6.3

**Comment by darktrojan** [comment]
Interesting. Is that a "full" theme or one of those "just like normal but with a background picture" themes? It looks like the latter but I thought I'd ask just in case.

**Comment by yym2** [comment]
Even if I use the default theme, it is the same, here is the screenshot.


-- 
Jerry Liu
Sent with Airmail

On 4 December 2015 at 23:06:30, Geoff Lankow (notifications@github.com) wrote:

Interesting. Is that a "full" theme or one of those "just like normal but with a background picture" themes? It looks like the latter but I thought I'd ask just in case.

**Comment by darktrojan** [comment]
Was this okay and then broken by something updating? What about other add-ons you have installed? Try disabling them a few at a time to see if something is interfering.

**Comment by yym2** [comment]
I log into the Guest Account with a fresh start, installed Open With only, same problem.


-- 
Jerry Liu
Sent with Airmail

On 4 December 2015 at 23:25:51, Geoff Lankow (notifications@github.com) wrote:

Was this okay and then broken by something updating? What about other add-ons you have installed? Try disabling them a few at a time to see if something is interfering.

**Comment by yym2** [comment]
<img width="1077" alt="screen shot 2015-12-05 at 11 31 08 am" src="https://cloud.githubusercontent.com/assets/4157030/11603978/c4922f06-9b4b-11e5-8fbb-88156b52ad69.png">

**Comment by darktrojan** [comment]
Okay, I think I know what's causing this. It would only affect retina Macs, but I'm surprised it hasn't been reported before.

I've created a new branch `osx` with a fix, but I have no way of testing it myself. [Here's a copy including the changes.](https://www.dropbox.com/s/ce3lj9se4totyp3/openwith%40darktrojan.net-6.3.xpi?dl=0)

**Comment by yym2** [comment]
Hi there,

It works. Thank you.

-- 
Jerry Liu
Sent with Airmail

On 5 December 2015 at 15:03:07, Geoff Lankow (notifications@github.com) wrote:

Okay, I think I know what's causing this. It would only affect retina Macs, but I'm surprised it hasn't been reported before.

I've created a new branch osx with a fix, but I have no way of testing it myself. Here's a copy including the changes.

**Comment by yym2** [comment]
Hi there, 

Since the one you give me is a unsigned add-on, Firefox will always tried to update it to an signed one and bring the bug back every now and then. Could you update the signed version please?

-- 
Jerry Liu
Sent with Airmail

On 5 December 2015 at 15:05:39, Jerry Liu (xgdd2@me.com) wrote:

Hi there,

It works. Thank you.

-- 
Jerry Liu
Sent with Airmail

On 5 December 2015 at 15:03:07, Geoff Lankow (notifications@github.com) wrote:

Okay, I think I know what's causing this. It would only affect retina Macs, but I'm surprised it hasn't been reported before.

I've created a new branch osx with a fix, but I have no way of testing it myself. Here's a copy including the changes.

**Comment by darktrojan** [comment]
Actually what's happened is the add-ons website has changed the version number of the current version (which I'm not very happy about) – if it hadn't changed you wouldn't be getting 'updates'. I'll put out a new version shortly including the fix for this bug, I'm just checking if there's anything else to be done first.

**Comment by darktrojan** [comment]
New version's been reviewed. You'll get it next time Firefox checks.
