### ISSUE TITLE
No context menu on bookmarks in the bookmarks toolbar

### ISSUE THREAD

**Issue by leos** [darktrojan/openwith#94]
Firefox 44.0.2, OS X 10.11.3

Right clicking on a bookmark in the Bookmarks Toolbar doesn't show the Open With items in the context menu. This is only for bookmarks shown on the Bookmarks Toolbar. The bookmarks on the menu triggered by the chevron on the right side of the Bookmarks Toolbar (the overflow) properly show Open With context menu items. Also, strangely, the context items show up properly for folders displayed on the Bookmarks Toolbar.

This definitely used to work and broke at some point in the past few weeks. Please let me know if I can provide any other info.
<img width="164" alt="folder" src="https://cloud.githubusercontent.com/assets/214370/13287124/5e475c4a-dad3-11e5-8e24-84c63c4421e1.png">
<img width="198" alt="regular item" src="https://cloud.githubusercontent.com/assets/214370/13287125/5e4bfa66-dad3-11e5-9651-9515decad6fa.png">

**Comment by darktrojan** [comment]
Oh, that's not good. This has been broken since October. I changed something and mistakenly made things show up for the items with dropdowns, not the ones without dropdowns. Thank you.

**Comment by leos** [comment]
Or slightly more than a few weeks :-) Thanks for fixing so quickly!
