### ISSUE TITLE
Add Open With menu item to HTML5 video right-click menu

### ISSUE THREAD

**Issue by medhefgo** [darktrojan/openwith#98]
HTML5 videos with the stock Firefox right-click menu does not show the Open With item list. It would be nice if there was, so you can easily watch in your favorite player instead of having to copy the video URL or clicking on View Video and then using the Open With tab menu.

To test, go to http://www.quirksmode.org/html5/tests/video.html and right click on one of the HTML5 videos.

**Comment by Link-Satonaka** [comment]
You might be interested to know that you can use youtube-dl to extract a video URL from most pages, and pass that along to your favorite player in a script.

The player mpv uses youtube-dl automatically, as long as it is in the same folder (or available on PATH). Set mpv as an "open with" entry using this extension to get this functionality.

**Comment by medhefgo** [comment]
I am well aware of that. But most isn't all pages.

**Comment by Link-Satonaka** [comment]
Are you also aware that your request is well outside the scope of this project? This is more in the domain of something like TamperData.

**Comment by medhefgo** [comment]
How is it out of scope to want the normal open with sub menu, that you can add to almost any other menus already, to be available in video submenus? -.-

**Comment by darktrojan** [comment]
It is out-of-scope as Open With has always been about pages, not the *content* of pages, *but* I do know that there are people out there using it for that, so I would consider a PR to make this change.

**Comment by moebiuseye** [comment]
I'd support this feature, **as an option**. :+1:

**Comment by flurbo2** [comment]
Fixed in #217 for most cases.
Please test it and let me know.
